try:
    print(num)
except NameError:
    print("there is a mistake")